name: GitHub Actions Demo
on: [push]
jobs:

  GeneratePDF:
    runs-on: ubuntu-latest
    container: mipmip/frontmatter-md-to-pdf:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Create PDF
        continue-on-error: true
        run: |
          echo "-----\n"
          ls -al

          echo "-----\n"
          pandoc -v

          echo "-----\n"
          fred version

          echo "-----\n"
          pwd

          cp -av example/dotpandoc/ ~/.pandoc

          echo "-----\n"
          mkdir build

          echo "-----\n"
          fred process_frontmatter_specials -d example/README.md  | sed 's/\\\[\\\[.*\\\]\\\]//g' > build/temp.md

          echo "-----\n"
          cp -av example/dotpandoc/ ~/.pandoc
          pandocomatic -b -i build/temp.md -o build/README.pdf

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
          branch: pdf
