name: Generate PDF
on: [push]
jobs:

  GeneratePDF:
    runs-on: ubuntu-latest
    container: mipmip/frontmatter-md-to-pdf:latest

    # EDIT ENV VARS BELOW TO SUIT YOUR CONF
    env:
      PANDOC_CONF_PATH: example/dotpandoc
      INPUT_FILE_PATH: example/README.md
      OUTPUT_FILE_NAME: README.pdf
      DEPLOY_BRANCH: pdf

    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Create PDF
        #continue-on-error: true
        run: |
          mkdir build
          fred process_frontmatter_specials -d ${INPUT_FILE_PATH} | sed 's/\\\[\\\[.*\\\]\\\]//g' > build/temp.md
          rsync -av ${PANDOC_CONF_PATH}/ ~/.pandoc/
          pandocomatic -b -i build/temp.md -o build/${OUTPUT_FILE_NAME}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: "${DEPLOY_BRANCH}"
